name: 'Telegram Message Notify'
description: 'Sending a Telegram message'
author: 'Bo-Yi Wu'
inputs:
  to:
    description: 'telegram user'
  token:
    description: 'telegram token'
  message:
    description: 'telegram message'
  message_file:
    description: 'overwrite the default message template with the contents of the specified file'
  socks5:
    description: 'support socks5 proxy URL'
  photo:
    description: 'send the photo message.'
  document:
    description: 'send the document message.'
  sticker:
    description: 'send the sticker message.'
  audio:
    description: 'send the audio message.'
  voice:
    description: 'send the voice message.'
  location:
    description: 'send the location message.'
  venue:
    description: 'send the venue message.'
  video:
    description: 'send the video message.'
  debug:
    description: 'enable debug mode.'
  format:
    description: 'message format: markdown or html'
  webpage_preview:
    description: 'disables link previews for links in this message'
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'message-square'
  color: 'blue'
